external_data_config:
  external_data_csv: data/external/filtered_data_city1.csv
  external_prod_data_csv: data/external/filtered_data_city1_v2.csv

data_process_config:
  city_id : 1
  last_hours : 24
  train_test_split_ratio: 0.2 
  random_state: 42

mlflow_config:
  artifacts_dir: artifacts
  experiment_name: my_experiment
  run_name: linear_regression
  registered_model_name: linear_regression_model
  remote_server_uri: http://localhost:5000 # http://127.0.0.1:5000/
 
linear_regression: 
  fit_intercept: False
  
production_config:
    min_mae_run_id: 90916f14ff644f6d9e517862aa7b08cf
    model_dir: models/model.joblib

#model_webapp_dir: webapp/model_webapp_dir/model.joblib
# model_monitor:
#  target_col_name: target
#  monitor_dashboard_html: reports/data_and_target_drift_dashboard.html
